sudo: required

language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "at-12"
    token: ${SONAR_TOKEN}

script:
  - ./gradlew check
  - sonar-scanner
  - ./gradlew runTests -Pkey=$TRELLO_KEY -Ptoken=$TRELLO_TOKEN -Prpuuid=$RP_UUID -P rplaunch=$RP_LAUNCH -Prpproject=$RP_PROJECT
